# Generated by Django 3.2 on 2021-04-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDonChuoiKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hoa_don', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tong_tien', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
                ('bao_hiem', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Hóa Đơn Chuỗi Khám',
                'verbose_name_plural': ('Hóa Đơn Chuỗi Khám',),
                'permissions': (('can_checkout_service_receipt', 'Thanh toán hóa đơn dịch vụ kỹ thuật'), ('can_view_service_receipt', 'Xem hóa đơn dịch vụ kỹ thuật'), ('can_delete_service_receipt', 'Xóa hóa đơn dịch vụ kỹ thuật'), ('can_print_service_receipt', 'In hóa đơn dịch vụ kỹ thuật'), ('can_view_service_expense_coverage', 'Xem danh sách dịch vụ kỹ thuật bảo hiểm chi trả'), ('can_export_service_expense_coverage', 'Xuất danh sách dịch vụ kỹ thuật bảo hiểm chi trả'), ('can_view_service_revenue', 'Xem doanh thu dịch vụ kỹ thuật')),
            },
        ),
        migrations.CreateModel(
            name='HoaDonLamSang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_tien', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hóa Đơn Lâm Sàng',
                'verbose_name_plural': ('Hóa Đơn Lâm Sàng',),
                'permissions': (('can_checkout_clinical_receipt', 'Thanh toán hóa đơn lâm sàng'), ('can_view_clinical_receipt', 'Xem hóa đơn lâm sàng'), ('can_delete_clinical_receipt', 'Xóa hóa đơn lâm sàng'), ('can_view_clinical_revenue', 'Xem doanh thu lâm sàng')),
            },
        ),
        migrations.CreateModel(
            name='HoaDonNhapHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hoa_don', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hóa Đơn Nhập Hàng',
            },
        ),
        migrations.CreateModel(
            name='HoaDonThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hoa_don', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tong_tien', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
                ('bao_hiem', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Hóa Đơn Thuốc',
                'verbose_name_plural': ('Hóa Đơn Thuốc',),
                'permissions': (('can_checkout_medicine_receipt', 'Thanh toán hóa đơn thuốc'), ('can_view_medicine_receipt', 'Xem hóa đơn thuốc'), ('can_delete_medicine_receipt', 'Xóa hóa đơn thuốc'), ('can_print_medicine_receipt', 'In hóa đơn thuốc'), ('can_view_medicine_expense_coverage', 'Xem danh sách thuốc bảo hiểm chi trả'), ('can_export_medicine_expense_coverage', 'Xuất danh sách thuốc bảo hiểm chi trả'), ('can_view_medicine_revenue', 'Xem doanh thu thuốc')),
            },
        ),
        migrations.CreateModel(
            name='HoaDonTong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bao_hiem', models.BooleanField(default=False)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDonTonHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hoa_don', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hóa Đơn Tồn Hàng',
            },
        ),
        migrations.CreateModel(
            name='HoaDonVatTu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_tien', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('bao_hiem', models.BooleanField(default=False)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hóa Đơn Vật Tư Y Tế',
                'verbose_name_plural': ('Hóa Đơn Vật Tư Y Tế',),
                'permissions': (('can_checkout_medical_supplies_receipt', 'Thanh toán hóa đơn vật tư y tế'), ('can_view_medical_supplies_receipt', 'Xem hóa đơn vật tư y tế'), ('can_delete_medical_supplies_receipt', 'Xóa hóa đơn vật tư y tế'), ('can_print_medical_supplies_receipt', 'In hóa đơn vật tư y tế'), ('can_view_medical_supplies_expense_coverage', 'Xem danh sách vật tư y tế bảo hiểm chi trả'), ('can_export_medical_supplies_expense_coverage', 'Xuất danh sách vật tư y tế bảo hiểm chi trả'), ('can_view_medical_supplies_revenue', 'Xem doanh thu vật tư y tế')),
            },
        ),
        migrations.CreateModel(
            name='HoaDonXuatHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hoa_don', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hóa Đơn Xuất Hàng',
            },
        ),
        migrations.CreateModel(
            name='NhapHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(blank=True, null=True)),
                ('bao_hiem', models.BooleanField(default=False)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Nhập Hàng',
            },
        ),
        migrations.CreateModel(
            name='TonHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField()),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
                ('hoa_don', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.hoadontonhang')),
            ],
            options={
                'verbose_name': 'Tồn Hàng',
            },
        ),
    ]
