# Generated by Django 3.2 on 2021-05-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20210518_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadonchuoikham',
            name='thoi_gian_thanh_toan',
        ),
        migrations.RemoveField(
            model_name='hoadonlamsang',
            name='thoi_gian_thanh_toan',
        ),
        migrations.RemoveField(
            model_name='hoadonthuoc',
            name='thoi_gian_thanh_toan',
        ),
    ]
