# Generated by Django 3.2 on 2021-05-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20210518_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadonchuoikham',
            name='thoi_gian_cap_nhat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoadonchuoikham',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoadonlamsang',
            name='thoi_gian_cap_nhat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoadonlamsang',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoadonthuoc',
            name='thoi_gian_cap_nhat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoadonthuoc',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
