# Generated by Django 3.2 on 2021-04-24 18:22

import clinic.models
from django.conf import settings
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ma_benh_nhan', models.CharField(max_length=20, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('so_dien_thoai', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='(84|0[3|5|7|8|9])+([0-9]{8})\\b')])),
                ('ho_ten', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cmnd_cccd', models.CharField(max_length=13, null=True, unique=True)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('gioi_tinh', models.CharField(blank=True, choices=[('1', 'Nam'), ('2', 'Nữ'), ('3', 'Không xác định')], max_length=10, null=True)),
                ('can_nang', models.PositiveIntegerField(blank=True, null=True)),
                ('anh_dai_dien', models.FileField(blank=True, max_length=1000, null=True, upload_to=clinic.models.file_url)),
                ('dia_chi', models.TextField(blank=True, max_length=1000, null=True)),
                ('dan_toc', models.CharField(blank=True, max_length=40, null=True)),
                ('chuc_nang', models.CharField(choices=[('1', 'Người Dùng'), ('2', 'Lễ Tân'), ('3', 'Bác Sĩ Lâm Sàng'), ('4', 'Bác Sĩ Chuyên Khoa'), ('5', 'Nhân Viên Phòng Tài Chính'), ('6', 'Nhân Viên Phòng Thuốc'), ('7', 'Quản Trị Viên')], default='1', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('superuser', models.BooleanField(default=False)),
                ('ma_so_bao_hiem', models.CharField(blank=True, max_length=25, null=True)),
                ('ma_dkbd', models.CharField(blank=True, max_length=10, null=True)),
                ('ma_khuvuc', models.CharField(blank=True, max_length=10, null=True)),
                ('gt_the_tu', models.DateField(blank=True, null=True)),
                ('gt_the_den', models.DateField(blank=True, null=True)),
                ('mien_cung_ct', models.DateField(blank=True, null=True)),
                ('lien_tuc_5_nam_tu', models.DateField(blank=True, null=True)),
                ('muc_huong', models.PositiveIntegerField(blank=True, null=True)),
                ('so_diem_tich', models.PositiveIntegerField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'permissions': (('can_add_user', 'Thêm người dùng'), ('can_add_staff_user', 'Thêm nhân viên'), ('can_change_user_info', 'Chỉnh sửa người dùng'), ('can_change_staff_user_info', 'Chỉnh sửa nhân viên'), ('can_change_password_user', 'Thay đổi mật khẩu người dùng'), ('can_change_password_staff_user', 'Thay đổi mật khẩu nhân viên'), ('can_view_user_info', 'Xem người dùng'), ('can_view_staff_user_info', 'Xem nhân viên'), ('can_delete_user', 'Xóa người dùng'), ('can_delete_staff_user', 'Xóa nhân viên'), ('general_view', 'Xem Tổng Quan Trang Chủ'), ('reception_department_module_view', 'Phòng Ban Lễ Tân'), ('finance_department_module_view', 'Phòng Ban Tài Chính'), ('specialist_department_module_view', 'Phòng Ban Chuyên Gia'), ('preclinical_department_module_view', 'Phòng Ban Lâm Sàng'), ('medicine_department_module_view', 'Phòng Ban Thuốc'), ('general_revenue_view', 'Xem Doanh Thu Phòng Khám'), ('can_view_checkout_list', 'Xem Danh Sách Thanh Toán Tài Chính'), ('export_insurance_data', 'Xuất Bảo Hiểm Tài Chính'), ('can_export_list_of_patient_insurance_coverage', 'Xuất Danh Sách Bệnh Nhân Bảo Hiểm Chi Trả'), ('can_view_list_of_patient', 'Xem Danh Sách Bệnh Nhân Chờ'), ('can_bao_cao_thuoc', 'Báo Cáo Thuốc')),
            },
        ),
        migrations.CreateModel(
            name='ChiSoXetNghiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_chi_so', models.CharField(blank=True, max_length=10, null=True)),
                ('ten_chi_so', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Chỉ Số Xét Nghiệm',
                'verbose_name_plural': 'Chỉ Số Xét Nghiệm',
                'permissions': (('can_add_test_values', 'Thêm chỉ số xét nghiệm'), ('can_change_test_values', 'Thay đổi chỉ số xét nghiệm'), ('can_view_test_values', 'Xem chỉ số xét nghiệm'), ('can_delete_test_values', 'Xóa chỉ số xét nghiệm')),
            },
        ),
        migrations.CreateModel(
            name='ChiTietChiSoXetNghiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_so_binh_thuong_min', models.CharField(blank=True, max_length=10, null=True)),
                ('chi_so_binh_thuong_max', models.CharField(blank=True, max_length=10, null=True)),
                ('chi_so_binh_thuong', models.CharField(blank=True, max_length=10, null=True)),
                ('don_vi_do', models.CharField(blank=True, max_length=50, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Chi Tiết Chỉ Số Xét Nghiệm',
                'verbose_name_plural': 'Chi Tiết Chỉ Số Xét Nghiệm',
            },
        ),
        migrations.CreateModel(
            name='ChuoiKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lk', models.CharField(blank=True, max_length=100, null=True)),
                ('thoi_gian_bat_dau', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_tai_kham', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True, null=True)),
                ('bac_si_dam_nhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bac_si_chuoi_kham', to=settings.AUTH_USER_MODEL)),
                ('benh_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuoi_kham', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chuỗi Khám',
                'verbose_name_plural': 'Chuỗi Khám',
                'permissions': (('can_add_assignment_chain', 'Thêm chuỗi khám'), ('can_change_assignment_chain', 'Thay đổi chuỗi khám'), ('can_view_assignment_chain', 'Xem chuỗi khám'), ('can_view_assignment_chain_result', 'Xem kết quả chuỗi khám'), ('can_delete_assignment_chain', 'Xóa chuỗi khám'), ('can_delete_assignment_chain_result', 'Xóa kết quả chuỗi khám')),
            },
        ),
        migrations.CreateModel(
            name='DanhMucBenh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_benh', models.CharField(blank=True, max_length=15, null=True)),
                ('ten_benh', models.CharField(blank=True, max_length=1024, null=True)),
                ('ma_nhom_bcao_byt', models.CharField(blank=True, max_length=5, null=True)),
                ('ma_nhom_chi_tiet', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Danh Mục Bệnh',
                'verbose_name_plural': 'Danh Mục Bệnh',
            },
        ),
        migrations.CreateModel(
            name='DanhMucChuongBenh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.CharField(blank=True, max_length=5, null=True)),
                ('ma_chuong', models.CharField(blank=True, max_length=15, null=True)),
                ('ten_chuong', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Danh Mục Chương Bệnh',
                'verbose_name_plural': 'Danh Mục Chương Bệnh',
            },
        ),
        migrations.CreateModel(
            name='DanhMucKhoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.IntegerField(blank=True, null=True)),
                ('ma_khoa', models.CharField(blank=True, max_length=5, null=True)),
                ('ten_khoa', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Danh Mục Khoa',
                'verbose_name_plural': 'Danh Mục Khoa',
            },
        ),
        migrations.CreateModel(
            name='DichVuKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dvkt', models.CharField(blank=True, max_length=50, null=True)),
                ('stt', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('ten_dvkt', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_gia', models.CharField(blank=True, max_length=50, null=True)),
                ('don_gia', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('don_gia_bhyt', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('quyet_dinh', models.CharField(blank=True, max_length=10, null=True)),
                ('cong_bo', models.CharField(blank=True, max_length=10, null=True)),
                ('ma_cosokcb', models.CharField(blank=True, max_length=20, null=True)),
                ('ten_dich_vu', models.CharField(blank=True, max_length=255, null=True)),
                ('bao_hiem', models.BooleanField(default=False)),
                ('tyle_tt', models.IntegerField(blank=True, null=True)),
                ('chi_so', models.BooleanField(default=False)),
                ('html', models.BooleanField(default=False)),
                ('khoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.danhmuckhoa')),
            ],
            options={
                'verbose_name': 'Dịch Vụ Khám',
                'verbose_name_plural': 'Dịch Vụ Khám',
                'permissions': (('can_add_service', 'Thêm dịch vụ kỹ thuật'), ('can_add_service_with_excel_file', 'Thêm dịch vụ kỹ thuật bằng Excel File'), ('can_change_service', 'Thay đổi dịch vụ kỹ thuật'), ('can_view_service', 'Xem dịch vụ kỹ thuật'), ('can_delete_service', 'Xóa dịch vụ kỹ thuật'), ('can_view_service_price', 'Xem giá dịch vụ kỹ thuật'), ('can_export_list_of_service', 'Xuất danh sách dịch vụ kỹ thuật')),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoTuoiXetNghiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_tuoi_min', models.PositiveIntegerField(blank=True, null=True)),
                ('do_tuoi_max', models.PositiveIntegerField(blank=True, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Độ Tuổi Xét Nghiệm',
                'verbose_name_plural': 'Độ Tuổi Xét Nghiệm',
            },
        ),
        migrations.CreateModel(
            name='DuongDungThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.IntegerField(blank=True, null=True)),
                ('ma_duong_dung', models.CharField(blank=True, max_length=5, null=True)),
                ('ten_duong_dung', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Đường Dùng Thuốc',
                'verbose_name_plural': 'Đường Dùng Thuốc',
            },
        ),
        migrations.CreateModel(
            name='FileKetQua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=clinic.models.file_url)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tài Liệu',
                'verbose_name_plural': 'Tài Liệu',
            },
        ),
        migrations.CreateModel(
            name='FilePhongKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=clinic.models.file_url)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tài Liệu Phòng Khám',
                'verbose_name_plural': 'Tài Liệu Phòng Khám',
            },
        ),
        migrations.CreateModel(
            name='GoiThau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_goi', models.CharField(blank=True, max_length=5, null=True)),
                ('goi', models.CharField(blank=True, max_length=255, null=True)),
                ('nhom', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_nhom', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Gói Thầu',
                'verbose_name_plural': 'Gói Thầu',
            },
        ),
        migrations.CreateModel(
            name='KetQuaChuyenKhoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_ket_qua', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True)),
                ('ket_luan', models.TextField(blank=True, null=True)),
                ('chi_so', models.BooleanField(default=False)),
                ('html', models.BooleanField(default=False)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('bac_si_chuyen_khoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ket_qua_bac_si_chuyen_khoa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kết Quả Chuyên Khoa',
                'verbose_name_plural': 'Kết Quả Chuyên Khoa',
                'permissions': (('can_add_specialty_result', 'Thêm kết quả chuyên khoa'), ('can_view_specialty_result', 'Xem kết quả chuyên khoa'), ('can_change_specialty_result', 'Thay đổi kết quả chuyên khoa'), ('can_delete_specialty_result', 'Xóa kết quả chuyên khoa'), ('can_view_history_specialty_result', 'Xem lịch sử khám chuyên khoa')),
            },
        ),
        migrations.CreateModel(
            name='LichHenKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lich_hen', models.CharField(blank=True, max_length=15, null=True)),
                ('thoi_gian_bat_dau', models.DateTimeField()),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('ly_do', models.TextField(blank=True, null=True)),
                ('dia_diem', models.CharField(blank=True, max_length=255, null=True)),
                ('loai_dich_vu', models.CharField(blank=True, choices=[('kham_chua_benh', 'Khám Chữa Bệnh'), ('kham_suc_khoe', 'Khám Sức Khỏe')], max_length=25, null=True)),
                ('ly_do_vvien', models.CharField(blank=True, choices=[('1', 'Đúng Tuyến'), ('2', 'Cấp Cứu'), ('3', 'Trái Tuyến'), ('4', 'Thông Tuyến')], max_length=5, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_chinh_sua', models.DateTimeField(auto_now=True, null=True)),
                ('benh_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benh_nhan_hen_kham', to=settings.AUTH_USER_MODEL)),
                ('nguoi_phu_trach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_phu_trach', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch Hẹn Khám',
                'verbose_name_plural': 'Lịch Hẹn Khám',
                'permissions': (('can_add_appointment', 'Thêm lịch hẹn'), ('can_change_appointment', 'Thay đổi lịch hẹn'), ('can_view_appointment', 'Xem lịch hẹn'), ('can_delete_appointment', 'Xóa lịch hẹn'), ('can_make_reexamination', 'Thêm lịch hẹn tái khám'), ('can_confirm_appoinment', 'Xác nhận lịch hẹn'), ('can_confirm_do_examination', 'Xác nhận khám')),
            },
        ),
        migrations.CreateModel(
            name='NhomChiPhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhom', models.CharField(blank=True, max_length=2, null=True)),
                ('ten_nhom', models.CharField(blank=True, max_length=255, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Nhóm Chi Phí',
                'verbose_name_plural': 'Nhóm Chi Phí',
            },
        ),
        migrations.CreateModel(
            name='NhomTaiNan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhom', models.CharField(blank=True, max_length=2, null=True)),
                ('ten_nhom', models.CharField(blank=True, max_length=100, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Nhóm Tai Nạn',
                'verbose_name_plural': 'Nhóm Tai Nạn',
            },
        ),
        migrations.CreateModel(
            name='PhongChucNang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong_chuc_nang', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True, null=True)),
                ('bac_si_phu_trach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bac_si_chuyen_khoa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phòng Chức Năng',
                'verbose_name_plural': 'Phòng Chức Năng',
                'permissions': (('can_add_consulting_room', 'Thêm phòng chức năng'), ('can_change_consulting_room', 'Chỉnh sửa phòng chức năng'), ('can_view_consulting_room', 'Xem phòng chức năng'), ('can_delete_consulting_room', 'Xóa phòng chức năng')),
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThietBi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_may', models.CharField(blank=True, max_length=50, null=True)),
                ('ten_may', models.CharField(blank=True, max_length=255, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Thiết Bị',
                'verbose_name_plural': 'Thiết Bị',
            },
        ),
        migrations.CreateModel(
            name='TinhTrangPhongKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kha_dung', models.BooleanField(default=True)),
                ('thoi_gian_dong_cua', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_mo_cua', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longtitude', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_range_start', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_range_end', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tình Trạng Phòng Khám',
                'verbose_name_plural': 'Tình Trạng Phòng Khám',
            },
        ),
        migrations.CreateModel(
            name='TrangThaiChuoiKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai_chuoi_kham', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Trạng Thái Chuỗi Khám',
                'verbose_name_plural': 'Trạng Thái Chuỗi Khám',
            },
        ),
        migrations.CreateModel(
            name='TrangThaiKhoaKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai_khoa_kham', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Trạng Thái Khoa Khám',
                'verbose_name_plural': 'Trạng Thái Khoa Khám',
            },
        ),
        migrations.CreateModel(
            name='TrangThaiLichHen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_trang_thai', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Trạng Thái Lịch Hẹn',
                'verbose_name_plural': 'Trạng Thái Lịch Hẹn',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='clinic.district')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhongChucNang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_cho', models.PositiveIntegerField(blank=True, null=True)),
                ('thoi_gian_trung_binh', models.PositiveIntegerField(blank=True, help_text='Đơn vị(phút)', null=True)),
                ('status', models.BooleanField(default=True)),
                ('phong_chuc_nang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_phong_chuc_nang', to='clinic.phongchucnang')),
            ],
        ),
        migrations.CreateModel(
            name='PhongKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_cskcb', models.CharField(blank=True, max_length=10, null=True)),
                ('ten_phong_kham', models.CharField(max_length=255)),
                ('dia_chi', models.TextField(blank=True, null=True)),
                ('so_dien_thoai', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to=clinic.models.file_url)),
                ('gia_tri_diem_tich', models.PositiveIntegerField(blank=True, null=True)),
                ('chu_khoan', models.CharField(blank=True, max_length=255, null=True)),
                ('so_tai_khoan', models.CharField(blank=True, max_length=20, null=True)),
                ('thong_tin_ngan_hang', models.TextField(blank=True, null=True)),
                ('tinh_trang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.tinhtrangphongkham')),
            ],
            options={
                'verbose_name': 'Phòng Khám',
                'verbose_name_plural': 'Phòng Khám',
                'permissions': (('can_add_clinic_info', 'Thêm thông tin phòng khám'), ('can_change_clinic_info', 'Thay đổi thông tin phòng khám')),
            },
        ),
        migrations.CreateModel(
            name='PhanKhoaKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bao_hiem', models.BooleanField(default=False)),
                ('priority', models.SmallIntegerField(blank=True, null=True)),
                ('thoi_gian_bat_dau', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True, null=True)),
                ('bac_si_lam_sang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bac_si', to=settings.AUTH_USER_MODEL)),
                ('benh_nhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chuoi_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phan_khoa_kham', to='clinic.chuoikham')),
                ('dich_vu_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phan_khoa_dich_vu', to='clinic.dichvukham')),
                ('trang_thai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.trangthaikhoakham')),
            ],
            options={
                'verbose_name': 'Phân Khoa Khám',
                'verbose_name_plural': 'Phân Khoa Khám',
                'permissions': (('can_add_service_assignment', 'Thêm phân khoa khám'), ('can_view_service_assignment', 'Xem phân khoa khám'), ('can_delete_service_assignment', 'Xóa phân khoa khám'), ('can_do_specialist_examination', 'Có thể khám chuyên khoa'), ('can_stop_serivce_assignment', 'Dừng khám')),
            },
        ),
        migrations.CreateModel(
            name='MauPhieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mau', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('noi_dung', models.TextField()),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(blank=True, null=True)),
                ('dich_vu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mau_phieu', to='clinic.dichvukham')),
            ],
            options={
                'verbose_name': 'Mẫu Phiếu',
                'verbose_name_plural': 'Mẫu Phiếu',
                'permissions': (('can_add_analysis_note', 'Thêm mẫu phiếu'), ('can_change_analysis_note', 'Thay đổi mẫu phiếu'), ('can_view_analysis_note', 'Xem mẫu phiếu'), ('can_delete_analysis_note', 'Xóa mẫu phiếu')),
            },
        ),
        migrations.CreateModel(
            name='LichSuTrangThaiLichHen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_tiet_trang_thai', models.CharField(blank=True, max_length=500, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('lich_hen_kham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_hen', to='clinic.lichhenkham')),
                ('trang_thai_lich_hen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trang_thai_lich_hen', to='clinic.trangthailichhen')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuTrangThaiKhoaKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_tiet_trang_thai', models.CharField(blank=True, max_length=500, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('phan_khoa_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.phankhoakham')),
                ('trang_thai_khoa_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.trangthaikhoakham')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuChuoiKham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_tiet_trang_thai', models.CharField(blank=True, max_length=500, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('chuoi_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.chuoikham')),
                ('trang_thai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.trangthaichuoikham')),
            ],
        ),
        migrations.AddField(
            model_name='lichhenkham',
            name='trang_thai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.trangthailichhen'),
        ),
        migrations.CreateModel(
            name='KetQuaXetNghiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ket_qua_xet_nghiem', models.CharField(blank=True, max_length=50, null=True)),
                ('danh_gia_chi_so', models.CharField(blank=True, choices=[('1', 'Bình thường'), ('0', 'Bất bình thường')], max_length=5, null=True)),
                ('danh_gia_ghi_chu', models.CharField(blank=True, max_length=100, null=True)),
                ('chi_so_xet_nghiem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.chisoxetnghiem')),
                ('ket_qua_chuyen_khoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ket_qua_xet_nghiem', to='clinic.ketquachuyenkhoa')),
                ('phan_khoa_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.phankhoakham')),
            ],
            options={
                'verbose_name': 'Kết Quả Xét Nghiệm',
                'verbose_name_plural': 'Kết Quả Xét Nghiệm',
                'permissions': (('can_add_lab_result', 'Thêm kết quả xét nghiệm'), ('can_change_lab_result', 'Thay đổi kết quả xét nghiệm'), ('can_view_lab_result', 'Xem kết quả xét nghiệm'), ('can_delete_lab_result', 'Xóa kết quả xét nghiệm')),
            },
        ),
        migrations.CreateModel(
            name='KetQuaTongQuat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_ket_qua', models.CharField(blank=True, max_length=50, null=True)),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True)),
                ('ket_luan', models.TextField(blank=True, null=True)),
                ('ket_qua_dieu_tri', models.CharField(blank=True, choices=[('1', 'Khỏi'), ('2', 'Đỡ'), ('3', 'Không Thay Đổi'), ('4', 'Nặng Hơn'), ('5', 'Tử Vong')], max_length=5, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('chuoi_kham', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ket_qua_tong_quat', to='clinic.chuoikham')),
                ('ma_benh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.danhmucbenh')),
            ],
            options={
                'verbose_name': 'Kết Quả Tổng Quát',
                'verbose_name_plural': 'Kết Quả Tổng Quát',
                'permissions': (('can_add_general_result', 'Thêm kết quả tổng quát'), ('can_view_general_result', 'Xem kết quả tổng quát'), ('can_change_general_result', 'Thay đổi kết quả tổng quát'), ('can_delete_general_result', 'Xóa kết quả tổng quát')),
            },
        ),
        migrations.AddField(
            model_name='ketquachuyenkhoa',
            name='ket_qua_tong_quat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ket_qua_chuyen_khoa', to='clinic.ketquatongquat'),
        ),
        migrations.AddField(
            model_name='ketquachuyenkhoa',
            name='phan_khoa_kham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ket_qua_chuyen_khoa', to='clinic.phankhoakham'),
        ),
        migrations.CreateModel(
            name='HtmlKetQua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('ket_qua_chuyen_khoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='html_ket_qua', to='clinic.ketquachuyenkhoa')),
                ('ket_qua_tong_quat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='html_ket_qua_tong_quat', to='clinic.ketquatongquat')),
                ('phan_khoa_kham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.phankhoakham')),
            ],
            options={
                'verbose_name': 'Kết Quả Dạng HTML',
                'verbose_name_plural': 'Kết Quả Dạng HTML',
            },
        ),
        migrations.CreateModel(
            name='GiaDichVu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.DecimalField(decimal_places=3, max_digits=10)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thoi_gian_chinh_sua', models.DateTimeField(blank=True, null=True)),
                ('id_dich_vu_kham', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gia_dich_vu_kham', to='clinic.dichvukham')),
            ],
        ),
        migrations.CreateModel(
            name='FileKetQuaTongQuat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tong_quat', to='clinic.fileketqua')),
                ('ket_qua_tong_quat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_ket_qua_tong_quat', to='clinic.ketquatongquat')),
            ],
            options={
                'verbose_name': 'File Kết Quả Tổng Quát',
                'verbose_name_plural': 'File Kết Quả Tổng Quát',
            },
        ),
        migrations.CreateModel(
            name='FileKetQuaChuyenKhoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_chuyen_khoa', to='clinic.fileketqua')),
                ('ket_qua_chuyen_khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_ket_qua_chuyen_khoa', to='clinic.ketquachuyenkhoa')),
            ],
            options={
                'verbose_name': 'File Kết Quả Chuyên Khoa',
                'verbose_name_plural': 'File Kết Quả Chuyên Khoa',
            },
        ),
        migrations.CreateModel(
            name='DoiTuongXetNghiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gioi_tinh', models.CharField(blank=True, choices=[('1', 'Nam'), ('2', 'Nữ'), ('3', 'Chưa Xác Định')], max_length=5, null=True)),
                ('do_tuoi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.dotuoixetnghiem')),
            ],
            options={
                'verbose_name': 'Đối Tượng Xét Nghiệm',
                'verbose_name_plural': 'Đối Tượng Xét Nghiệm',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='clinic.province'),
        ),
        migrations.AddField(
            model_name='dichvukham',
            name='nhom_chi_phi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.nhomchiphi'),
        ),
        migrations.AddField(
            model_name='dichvukham',
            name='phong_chuc_nang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dich_vu_kham_theo_phong', to='clinic.phongchucnang'),
        ),
        migrations.CreateModel(
            name='DanhMucNhomBenh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhom_chinh', models.CharField(blank=True, max_length=15, null=True)),
                ('ten_nhom_chinh', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_nhom_phu_1', models.CharField(blank=True, max_length=15, null=True)),
                ('ten_nhom_phu_1', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_nhom_phu_2', models.CharField(blank=True, max_length=15, null=True)),
                ('ten_nhom_phu_2', models.CharField(blank=True, max_length=255, null=True)),
                ('chuong_benh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhom_benh', to='clinic.danhmucchuongbenh')),
            ],
            options={
                'verbose_name': 'Danh Mục Nhóm Bệnh',
                'verbose_name_plural': 'Danh Mục Nhóm Bệnh',
            },
        ),
        migrations.CreateModel(
            name='DanhMucLoaiBenh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_loai', models.CharField(blank=True, max_length=10, null=True)),
                ('ten_loai', models.CharField(blank=True, max_length=255, null=True)),
                ('nhom_benh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loai_benh', to='clinic.danhmucnhombenh')),
            ],
            options={
                'verbose_name': 'Danh Mục Loại Bệnh',
                'verbose_name_plural': 'Danh Mục Loại Bệnh',
            },
        ),
        migrations.AddField(
            model_name='danhmucbenh',
            name='loai_benh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benh', to='clinic.danhmucloaibenh'),
        ),
        migrations.AddField(
            model_name='chuoikham',
            name='lich_hen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_sach_chuoi_kham', to='clinic.lichhenkham'),
        ),
        migrations.AddField(
            model_name='chuoikham',
            name='trang_thai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trang_thai', to='clinic.trangthaichuoikham'),
        ),
        migrations.AddField(
            model_name='chisoxetnghiem',
            name='chi_tiet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.chitietchisoxetnghiem'),
        ),
        migrations.AddField(
            model_name='chisoxetnghiem',
            name='dich_vu_kham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chi_so_xet_nghiem', to='clinic.dichvukham'),
        ),
        migrations.AddField(
            model_name='chisoxetnghiem',
            name='doi_tuong_xet_nghiem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doituongxetnghiem'),
        ),
        migrations.CreateModel(
            name='BaoHiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_bao_hiem', models.CharField(max_length=255)),
                ('dang_bao_hiem', models.SmallIntegerField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField()),
                ('thoi_gian_chinh_sua', models.DateTimeField()),
                ('id_dich_vu_kham', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bao_hiem_dich_vu_kham', to='clinic.dichvukham')),
            ],
        ),
        migrations.CreateModel(
            name='BaiDang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(blank=True, max_length=1024, null=True)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to=clinic.models.file_url)),
                ('noi_dung_chinh', models.TextField(blank=True, null=True)),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('thoi_gian_bat_dau', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('nguoi_dang_bai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_dang_bai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài Đăng',
                'verbose_name_plural': 'Bài Đăng',
                'permissions': (('can_add_news', 'Thêm bài đăng'), ('can_change_news', 'Thay đổi bài đăng'), ('can_view_news', 'Xem bài đăng'), ('can_delete_news', 'Xóa bài đăng')),
            },
        ),
        migrations.CreateModel(
            name='BacSi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chung_chi_hanh_nghe', models.CharField(blank=True, max_length=50, null=True)),
                ('gioi_thieu', models.TextField(blank=True, null=True)),
                ('chuc_danh', models.CharField(blank=True, max_length=255, null=True)),
                ('chuyen_khoa', models.CharField(blank=True, max_length=255, null=True)),
                ('noi_cong_tac', models.TextField(blank=True, null=True)),
                ('kinh_nghiem', models.TextField(blank=True, null=True)),
                ('loai_cong_viec', models.CharField(blank=True, choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time')], max_length=50, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bac_si', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bác Sĩ',
                'verbose_name_plural': 'Bác Sĩ',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='huyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.district'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.province'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='xa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.ward'),
        ),
    ]
