# Generated by Django 3.2 on 2021-04-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhenkham',
            name='thanh_toan_sau',
            field=models.BooleanField(default=False),
        ),
    ]
