# Generated by Django 3.2 on 2021-05-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20210501_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhomChiSoXetNghiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Nhóm Chỉ Số Xét Nghiệm',
                'verbose_name_plural': 'Nhóm Chỉ Số Xét Nghiệm',
            },
        ),
        migrations.AddField(
            model_name='chisoxetnghiem',
            name='nhom_chi_so',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.nhomchisoxetnghiem'),
        ),
    ]
